get exit code

diff --git a/.github/workflows/terratest.yml b/.github/workflows/terratest.yml
--- a/.github/workflows/terratest.yml
+++ b/.github/workflows/terratest.yml
@@ -77,6 +77,13 @@ jobs:
       run: |
         printenv | sort
         go test -v -timeout ${{ inputs.timeout }} | tee ${{ runner.temp }}/test_output.log
+        # if terratest runs, but tests fail, the exit code is 1
+        echo "go test exit code: ${PIPESTATUS[0]}"
+        if [ "${PIPESTATUS[0]}" != "1" ]; then
+          exit ${PIPESTATUS[0]}
+        else
+          exit 0
+        fi
       env:
         ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
         ARM_CLIENT_SECRET:  ${{ secrets.ARM_CLIENT_SECRET }}
